const express = require('express');
const { balanceWithdraw, withdrawTransAcction, withdrawStatusByHistory, getWithdrawSingle, myBalanceGet, myBalanceAdd } = require('../controllers/balanceWithdrawControllers');
const { protect } = require('../middlewares/authMiddleware');
const router = express.Router();
router.route('/balance/my').get(protect,myBalanceGet);
router.route('/my/balance-add').post(protect,myBalanceAdd);
router.route('/balance/withdraw').post(protect, balanceWithdraw);
router.route('/balance/withdraw/:id').get(protect,getWithdrawSingle);
router.route('/balance/withdraw/status/:id').put(protect, withdrawTransAcction);
router.route('/balance/withdraw/status/history').get(protect,withdrawStatusByHistory);
module.exports = router;