const express = require('express');
const { productCreate, productUpdate, productRemove, getSignleProduct, productStatusUpdate } = require('../controllers/productControllers');
const { protect } = require('../middlewares/authMiddleware');
const router = express.Router();
router.route('/products/create').post(protect, productCreate);
router.route('/products/update/:id').put(protect, productUpdate);
router.route('/products/remove/:id').delete(protect, productRemove);
router.route('/products/status/:id').put(protect, productStatusUpdate);
router.route('/products/singleProduct/:id').get(protect,getSignleProduct);
module.exports = router;